### ISSUE TITLE
wo hope it can play anime just like popcorn time

### ISSUE THREAD

**Issue by 1470391328** [Kylart/KawAnime#18]
wo hope it can play anime just like popcorn time,and support chinese language.beause many chinese like anime.

**Comment by JuanjoSalvador** [comment]
This could be a great feature.

**Comment by Kylart** [comment]
Sooo about streaming...

There are lots of things about streaming:
* It is no easy feature especially if we're talking about real "streaming" like downloading and watching at the same time. This is because KawAnime is based on torrents and watching torrents while downloading is not a good thing for torrents themselves. This can be overcome.
* The main problem is this one : KawAnime is made with web technologies. Also, most of the files you can download as of right now (it will get better) are mostly `mkv` files. `mkv` is a difficult format to work with and at this day, there is __no__ web video player that can read `mkv` file along with their "embed" subtitles.
* I do believe that I can do no better than `VLC` or some other apps out there.

So yea.. very interesting feature. Definitely planned but definitely not in top priority right now. It does need a lot of time and effort.

***
As of Chinese support. I know the Chinese community is very large when it comes to anime but there are two problems here:
1. I don't really know where to find torrents and sources in Chinese.
2. I do not speak Chinese at all 😞 . Thus it is really hard to find stuff.

What I can do though is implementing language translations in _KawAnime_ (probably with i18n) with Chinese in available languages. But then again, I would need:
1. People that can do translations.
2. Information site(s) (similar to myanimelist.net or livechart.me) in Chinese.

Internationalisation is actually a big problem in _KawAnime_ for not only translations are needed but also websites similar to the ones used currently.

**Comment by xdk78** [comment]
https://github.com/00SteinsGate00/Node-MPV
Pretty good, I'm using in https://github.com/NyaaPantsu/cinnamon

**Comment by Kylart** [comment]
```
This module requires mpv to be installed on your system to work
```

I do not want to use things that would require third-party application to be installed 🤕

**Comment by xdk78** [comment]
https://github.com/videojs/video.js

**Comment by xdk78** [comment]
or https://github.com/surmon-china/vue-video-player both I tested and ```.mkv``` should working

**Comment by Kylart** [comment]
Ok I was kinda unclear on this. The problem here isn't about reading `mkv` as a video file. The problem is that there is no player based on web-technologies that can read `mkv` along with the embed subtitles.

Don't get me wrong, you can watch the video just fine. But the subtitles won't appear. To try it you can try downloading one of the `HorribleSubs` video (just an example). This will be a `.mkv` file with `embed` subtitles. We don't have access to the `.ass` or any subtitle file. Then try to read it with `video-js` (There is no type "video/mkv" so you should use any other like "video/mp4"). This way you'll get to see the video but you won't see any subtitle.

`video-js` does support subtitles but it must be use like described [here](https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Adding_captions_and_subtitles_to_HTML5_video) (with `track` tag) as it is said in [this issue](https://github.com/videojs/video.js/issues/4265). 

Though, if you find a way to use `mkv` files with `embed` subtitles like those released by `HorribleSubs`, I would gladly appreciate any advice there 😄 .

**Comment by wopian** [comment]
[matroska-subtitles](https://www.npmjs.com/package/matroska-subtitles) may be of use

**Comment by xdk78** [comment]
Yes https://github.com/mathiasvr/matroska-subtitles

**Comment by Kylart** [comment]
This could work, would need a preprocessing before reading the file + writing some code that would transform the output to an actual `track` that could be used by `html`.

Nice one guys! Thanks 😄
