### ISSUE TITLE
Mobile Version

### ISSUE THREAD

**Issue by DemonRem** [Kylart/KawAnime#31]
what about mobile version ? it's can be good idea :)

**Comment by zunjae** [comment]
I don't believe this issue belongs here. This is an electron based application which can not run on mobile.

**Comment by JuanjoSalvador** [comment]
For a mobile version, the best way is building an streaming website, I guess.

**Comment by DeltaEvo** [comment]
@zunjae The architecture of this application is not very tied to electron so this might be possible, the only work needed here is just how to package it and try the responsiveness of the website

**Comment by DeltaEvo** [comment]
@JuanjoSalvador not really an anime website is just another solution to watch animes, both have they associated pros and cons

**Comment by Kylart** [comment]
> I don't believe this issue belongs here. This is an electron based application which can not run on mobile.

I would have preferred the question to be on Discord but it's fine here since not everyone is on Discord and people keep asking me 😄 . Still, as @DeltaEvo mentionned, `electron`, here in KawAnime is only a wrapper so it is definitely possible to port the actual app on mobile.

> For a mobile version, the best way is building an streaming website, I guess.

There are other ways to make KawAnime on mobile, there are `electron`-like frameworks that aims towards this purpose (native-script, vuex, ...).

As for the mobile version, I talked a lot about it in the Discord server so here's a sum up. There are important features I want to develop _before_ working on a mobile version (streaming, in-app nyaa browser, kitsu implementation etc...).

It is _planned_ and I'm already keeping an eye on the frameworks / librairies that would allow me to build a mobile app. Most likely, when you'll see KawAnime being at v1.0.0, this will mean that I'll then be working a lot on a mobile app.

I too, would really love to have KawAnime on my phone 😢

**Comment by Kylart** [comment]
I'm closing this for now as it's not really an issue, please do no hesitate to redirect people to this issue if needed. Also, feel free to comment here if you want to.
