### ISSUE TITLE
fresh interface

### ISSUE THREAD

**Issue by dhamarhusainsm** [Kylart/KawAnime#37]
actually the UI is now not bad, but I think by changing interface to make it more cool it will make more people interested.

**Comment by xdk78** [comment]
So, any idea?

**Comment by dhamarhusainsm** [comment]
i can help for UI/UX, but i'm not to familiar with vue

**Comment by Kylart** [comment]
I'm not against but  yea, I'd need or at least love sketches or design ideas, not necessarily code. Everything could be done imo.

**Comment by dhamarhusainsm** [comment]
![sample](https://preview.ibb.co/mAK4Dn/season_try.png)
@Kylart  I hope you like, and of course this is just an example

**Comment by xdk78** [comment]
I think this sketch should contain a little bit of material design elements

**Comment by dhamarhusainsm** [comment]
I see, applications that have been released also use material design.

**Comment by Kylart** [comment]
I kinda like the design you made, looks neat! The main point is that you removed the navigation drawer for a less "mobile" interface. I also see that the cards aren't the problem as you kept those. 

Main problem to me is that this looks a lot like a web app design especially the menu. While KawAnime _is_ a web app, it should have a more desktopish interface imo.

Material design is not a must, custom design or other graphics could work too. There are lots of good UI libraries out there.

Anyway, I'd love to see more, there are lots of good ideas in this simple page you designed!

**Comment by dhamarhusainsm** [comment]
I am happy to hear it, and for the next I will show it on the discord channel.

**Comment by RwbyChan** [comment]
I could always try to make something in between when I get some time

**Comment by feirydraco** [comment]
Do you think the application could also be ported to a PyQT native windows application, that would make it smoother and faster.

**Comment by Kylart** [comment]
So there hasn't been any news on this, I actually made a new design more user friendly imo, here's a preview of this
<img width="1280" alt="screenshot 2018-12-19 at 01 04 47" src="https://user-images.githubusercontent.com/18316666/50190597-22457d80-032a-11e9-9781-c16477bddf01.png">

This version is actually available on `master`. I only want to make the torrent client before releasing this version. Feel free to give me your feedback here or on the discord channel if you'd come to try it! 

I'm closing this issue since there hasn't been any update and a fresh interface has been made.
