### ISSUE TITLE
Install in android

### ISSUE THREAD

**Issue by Rawkush** [Kylart/KawAnime#43]
How to install this in android for dev

**Comment by Kylart** [comment]
This is made to be a desktop app so it cannot be installed on Android easily at all, there are ways to do it if you wanna dive into some code but I don't think that is what you asked. Still, let me know if you are interested.

**Comment by xdk78** [comment]
imho is better to create website that contain components from this app

**Comment by Rawkush** [comment]
yeah, I am interested in making one for android

**Comment by Kylart** [comment]
mmmh Are you sure? This is definitely no easy task. I can definitely help but I don't want it to be the main thing I'd working on right now.

So, basically, KawAnime comes from [this vuetify template](https://github.com/vuetifyjs/webpack-ssr) which I adapted for a desktop's use. So `server` files were not here and `server.js` in the template is `main.js` is here where I simply added the electron thingy.

There are different ways to somehow keep a nice proportion of the codebase to make a mobile app.
* Cordova, [Vuetify's team has made a template for it](https://github.com/vuetifyjs/cordova) so maybe you'd find help on their Discord server if you have question on how to switch from out structure to the Cordova structure.
* Ionic, there is no template from the vuetify's team and I don't it that much.
* NativeScript. Same as Ionic but I had my eyes on it for a while when considering a mobile app and I kinda liked its approach.

I am definitely no expert in the mobile app things. I have plans to make a mobile app but I cannot work on this and the desktop app at the same time especially when I have a full time job so I wanted to at least finish a first draft of all the main features I thought of and only one and a half are remaining.

The plans I investigated most was to rebuild everything with Google's `Flutter` framework. It is not node and Dart is kinda new so it would be a nice way to learn something new too.

I don't know if that helps, your question is really vague and I'm not entirely sure what it is you're asking / thinking.

**Comment by Kylart** [comment]
Sure. Just leave HorribleApi behind, no longer useful + outdated since horriblesubs changed their websites.

The most important libraries are the followings:
* `axios`: http requests.
* `express`: For the server.
* `vue` and `vueitfy`: Well the app is build on top of those for the all the UI.
* `nyaapi`: Gives access to all _nyaa.si_ and _nyaa.pantsu.cat_ for the magnets links to downlaod.
* `mal-scraper`: Allows to scrap MAL to get anime information. Also it offers the access to the offical MAL Api (which is still down currently..).
* `webtorrent`: To download torrents.

There are some others but they are not that vital for the app and they only bring more security / features.
