### ISSUE TITLE
Beyblade Burst Not Exists

### ISSUE THREAD

**Issue by DemonRem** [Kylart/KawAnime#50]
@Kylart 

from some reason the most popular anime Beyblade Burst not exist why is that?

i check the MyAnimeList Site i see it there also i tried many diffrent name even just Beyblade and nothing

**Comment by Kylart** [comment]
Because no supported subs have subbed it. As I said, fansub dependency is going to disapear in the next release so it will appear in the new UI researchs, with or without subs is not of my choice 😢 .

In the meantime, I made some research and I found only the raw episodes (no subs), you can find  the torrents [here](https://nyaa.si/?f=2&c=1_0&q=Beyblade+Burst+Chouzetsu).
