### ISSUE TITLE
Search results take longer to load and episodes are not listed

### ISSUE THREAD

**Issue by MikuHatsune39** [Kylart/KawAnime#65]
Search results take longer to load (or it freezes)  and episodes are not listed, it only lists cast and staff.

I tried searching for YuruYuri in the old version and the new version and these are the results.
(I've had similar results when searching for other shows.)
![kawanime](https://user-images.githubusercontent.com/32179075/66612743-d851bf00-ebfd-11e9-8859-753f36b51cba.png)

**Comment by Kylart** [comment]
Hello,

This seems like an issue, I'm not entirely sure how the old screenshot was taken. I guess you searched from the streaming page and went on with that.

Any way, this is a real problem, a quick fix seems possible to me. I'm gonna investigate this and possibly release it in the next version.

Keep in mind that this will _not_ happen for most animes. The problem here is that HorribleSubs has named this anime as `YuruYuri` when MyAnimeList (I think that's the provider you are using) calls it `Yuru Yuri`. So it's a naming problem. As long as the fansub uses the same name as the provider, you'll have the episode list with no problem.

Thank you for reporting this.
