### ISSUE TITLE
[feature request] watch list filter by currently watching

### ISSUE THREAD

**Issue by SaruDesu422** [Kylart/KawAnime#80]
it's just an idea that might help some users, me included, for usage of the app.

**Comment by Kylart** [comment]
Hello,

So I guess you are talking about the watch list of tier apps like MAL, Anilist and Kitsu.io.

There no built-in solution for that _however_ there is something that you can do already: you are able to search for status. which means that you can right in the search input `Watching` for e.g. for MAL and you will see only the entries that are set as watching, as you can see in the attached screenshot (design is a bit different because I'm using the dev version).
<img width="1281" alt="Screenshot 2020-12-02 at 03 23 57" src="https://user-images.githubusercontent.com/18316666/100820178-f60b6480-344d-11eb-8379-9825f06d8e94.png">

Equivalent search for Kitsu: `Current`
Equivalent seatch for Anilist: `Current`

Hope this helps!
